### ISSUE TITLE
Support These Land Claim Plugins

### ISSUE THREAD

**Issue by goflishMC** [promcteam/problockregen#18]
Add option to disable in residence claims: https://www.zrips.net/residence/api/sipg
Add option to disable in lands claims: https://github.com/Angeschossen/LandsAPI/wiki
Add option to disable in grief prevention claims: https://docs.griefprevention.com/api/
Add option to disable in protectionstones claims: https://github.com/espidev/ProtectionStones/wiki/API
Add option to disable in GriefDefender claims: https://github.com/bloodmc/GriefDefenderAPI

**Comment by Sentropic** [comment]
Should this be in the global config, or for each entry?
