### ISSUE TITLE
Could not pass event BlockBreakEvent to ProBlockRegen v1.0.2-4322224

### ISSUE THREAD

**Issue by VacAge** [promcteam/problockregen#29]
Problockregen - 1.0.2-43222
Server - 1.20.1
[mclo Error Log](https://mclo.gs/LDYHTpN)

**Comment by Sentropic** [comment]
Outdated version. Use at last 1.1.0, otherwise you need ProMCUtilities and RiseCore.

**Comment by VacAge** [comment]
> Outdated version. Use at last 1.1.0, otherwise you need ProMCUtilities and RiseCore.

I couldn't find such a version
